CC = g++
OBJS = stereo_calib.o
DEBUG = -g
CFLAGS = -Wall -c $(DEBUG)
LFLAGS = -Wall $(DEBUG)

stereo_calib : $(OBJS)
	$(CC) $(LFLAGS) $(OBJS) `pkg-config opencv --cflags --libs` -o stereo_calib

stereo_calib.o : stereo_calib.cpp
	$(CC) $(CFLAGS) stereo_calib.cpp

clean:
	\rm -f *.o

cleanall:
	\rm -f *.o stereo_calib
